name: "AniList-Studio"
guid: "c0de98ad-a1a5-4d2f-9b6d-383742f4d910"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 9
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "rzk3"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - Limit amount of people in metadata search result (#68) @AkaTenshi
  - Feature: Decouples VA filter from the title language, and moves to the new Anilist StaffLanguage API key (#65) @mmshivesh

  ### Dependency updates ###
  - Update dependency AnitomySharp.NET6 to v0.5.1 (#64) @renovate
